### PR TITLE
Apply upcoming fog shader changes

### PR DESCRIPTION
**Pull request by AbduSharif**
Please do not merge until this is merged:
https://gitlab.com/OpenMW/openmw/-/merge_requests/2006/

### CODE REVIEW

**Comment by AbduSharif** [comment]
The MR has been merged.

**Comment by AbduSharif** [comment]
Need to apply this too:
https://gitlab.com/OpenMW/openmw/-/merge_requests/2046

**Comment by AbduSharif** [comment]
This one is ready.

**Comment by zesterer** [comment]
Thanks!

**Pull request merged**
